//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSProcessManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Games\\Freelancer\\EXE\\FLServer.exe")]
        public string setFlEXE {
            get {
                return ((string)(this["setFlEXE"]));
            }
            set {
                this["setFlEXE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int setRestartTime {
            get {
                return ((int)(this["setRestartTime"]));
            }
            set {
                this["setRestartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public decimal setRestartMaxLoad {
            get {
                return ((decimal)(this["setRestartMaxLoad"]));
            }
            set {
                this["setRestartMaxLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public decimal setRestartMaxMemory {
            get {
                return ((decimal)(this["setRestartMaxMemory"]));
            }
            set {
                this["setRestartMaxMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1919")]
        public decimal setFLHookPort {
            get {
                return ((decimal)(this["setFLHookPort"]));
            }
            set {
                this["setFLHookPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string setFLHookPassword {
            get {
                return ((string)(this["setFLHookPassword"]));
            }
            set {
                this["setFLHookPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public decimal setStartupMaxReplyTime {
            get {
                return ((decimal)(this["setStartupMaxReplyTime"]));
            }
            set {
                this["setStartupMaxReplyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string setFLHookIP {
            get {
                return ((string)(this["setFLHookIP"]));
            }
            set {
                this["setFLHookIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDailyRestart {
            get {
                return ((bool)(this["setDailyRestart"]));
            }
            set {
                this["setDailyRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Notice to Space Farers : Long range probes indicates approaching ION storms in 10" +
            " minutes.")]
        public string setDailyRestartWarning10min {
            get {
                return ((string)(this["setDailyRestartWarning10min"]));
            }
            set {
                this["setDailyRestartWarning10min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sirius Meteorological Institute, Late Warning department leader, The Right Honour" +
            "able Fellow Hoodlum, Esq., confirms approaching ION storm will reach Sirius in 5" +
            " minutes. Proceed to nearest docking facility at best speed. ")]
        public string setDailyRestartWarning5min {
            get {
                return ((string)(this["setDailyRestartWarning5min"]));
            }
            set {
                this["setDailyRestartWarning5min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Outer rim Sirius research stations reports ION storms will hit in 1 minute. All v" +
            "essels are advised to dock now. Expected duration of system wide darkening to be" +
            " 12 minutes.")]
        public string setDailyRestartWarning1min {
            get {
                return ((string)(this["setDailyRestartWarning1min"]));
            }
            set {
                this["setDailyRestartWarning1min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\backup.bat")]
        public string setDailyExtCmd1 {
            get {
                return ((string)(this["setDailyExtCmd1"]));
            }
            set {
                this["setDailyExtCmd1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setDailyExtCmd2 {
            get {
                return ((string)(this["setDailyExtCmd2"]));
            }
            set {
                this["setDailyExtCmd2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int setDailyExtCmd1Time {
            get {
                return ((int)(this["setDailyExtCmd1Time"]));
            }
            set {
                this["setDailyExtCmd1Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int setDailyExtCmd2Time {
            get {
                return ((int)(this["setDailyExtCmd2Time"]));
            }
            set {
                this["setDailyExtCmd2Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/c /p2302")]
        public string setFLExeArgs {
            get {
                return ((string)(this["setFLExeArgs"]));
            }
            set {
                this["setFLExeArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setFLHookUnicode {
            get {
                return ((bool)(this["setFLHookUnicode"]));
            }
            set {
                this["setFLHookUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Games\\Freelancer\\EXE\\flhook_logs\\events.log")]
        public string setMainLogPath {
            get {
                return ((string)(this["setMainLogPath"]));
            }
            set {
                this["setMainLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\restart.bat")]
        public string setBeforeRestartExtCmd {
            get {
                return ((string)(this["setBeforeRestartExtCmd"]));
            }
            set {
                this["setBeforeRestartExtCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal setLogHighNetTrafficLimit {
            get {
                return ((decimal)(this["setLogHighNetTrafficLimit"]));
            }
            set {
                this["setLogHighNetTrafficLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal setGraphUpdateRate {
            get {
                return ((decimal)(this["setGraphUpdateRate"]));
            }
            set {
                this["setGraphUpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setBlockHighNetTraffic {
            get {
                return ((bool)(this["setBlockHighNetTraffic"]));
            }
            set {
                this["setBlockHighNetTraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Games\\Freelancer\\EXE\\flhook_logs\\chats.log")]
        public string setGameLogPath {
            get {
                return ((string)(this["setGameLogPath"]));
            }
            set {
                this["setGameLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2302")]
        public decimal setNetLowPort {
            get {
                return ((decimal)(this["setNetLowPort"]));
            }
            set {
                this["setNetLowPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2304")]
        public decimal setNetHighPort {
            get {
                return ((decimal)(this["setNetHighPort"]));
            }
            set {
                this["setNetHighPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setEnableNetMonitor {
            get {
                return ((bool)(this["setEnableNetMonitor"]));
            }
            set {
                this["setEnableNetMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setDebug {
            get {
                return ((decimal)(this["setDebug"]));
            }
            set {
                this["setDebug"] = value;
            }
        }
    }
}
